/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TokenFaucetInterface extends Interface {
    getFunction(nameOrSignature: "COOLDOWN_TIME" | "FAUCET_AMOUNT" | "MAX_CLAIM_AMOUNT" | "admin" | "canClaim" | "isPaused" | "lastClaimAt" | "paused" | "remainingAllowance" | "requestTokens" | "setPaused" | "token" | "totalClaimed"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FaucetPaused" | "TokensClaimed"): EventFragment;

    encodeFunctionData(functionFragment: 'COOLDOWN_TIME', values?: undefined): string;
encodeFunctionData(functionFragment: 'FAUCET_AMOUNT', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_CLAIM_AMOUNT', values?: undefined): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'canClaim', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isPaused', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastClaimAt', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'remainingAllowance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'requestTokens', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPaused', values: [boolean]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalClaimed', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'COOLDOWN_TIME', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FAUCET_AMOUNT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_CLAIM_AMOUNT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPaused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastClaimAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'remainingAllowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPaused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalClaimed', data: BytesLike): Result;
  }

  
    export namespace FaucetPausedEvent {
      export type InputTuple = [paused: boolean];
      export type OutputTuple = [paused: boolean];
      export interface OutputObject {paused: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensClaimedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint, timestamp: bigint];
      export interface OutputObject {user: string, amount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TokenFaucet extends BaseContract {
    
    connect(runner?: ContractRunner | null): TokenFaucet;
    waitForDeployment(): Promise<this>;

    interface: TokenFaucetInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    COOLDOWN_TIME: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FAUCET_AMOUNT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_CLAIM_AMOUNT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    canClaim: TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isPaused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    lastClaimAt: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    remainingAllowance: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    requestTokens: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setPaused: TypedContractMethod<
      [_paused: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalClaimed: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'COOLDOWN_TIME'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FAUCET_AMOUNT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_CLAIM_AMOUNT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'canClaim'): TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isPaused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lastClaimAt'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'remainingAllowance'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'requestTokens'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPaused'): TypedContractMethod<
      [_paused: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalClaimed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'FaucetPaused'): TypedContractEvent<FaucetPausedEvent.InputTuple, FaucetPausedEvent.OutputTuple, FaucetPausedEvent.OutputObject>;
getEvent(key: 'TokensClaimed'): TypedContractEvent<TokensClaimedEvent.InputTuple, TokensClaimedEvent.OutputTuple, TokensClaimedEvent.OutputObject>;

    filters: {
      
      'FaucetPaused(bool)': TypedContractEvent<FaucetPausedEvent.InputTuple, FaucetPausedEvent.OutputTuple, FaucetPausedEvent.OutputObject>;
      FaucetPaused: TypedContractEvent<FaucetPausedEvent.InputTuple, FaucetPausedEvent.OutputTuple, FaucetPausedEvent.OutputObject>;
    

      'TokensClaimed(address,uint256,uint256)': TypedContractEvent<TokensClaimedEvent.InputTuple, TokensClaimedEvent.OutputTuple, TokensClaimedEvent.OutputObject>;
      TokensClaimed: TypedContractEvent<TokensClaimedEvent.InputTuple, TokensClaimedEvent.OutputTuple, TokensClaimedEvent.OutputObject>;
    
    };
  }