/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tokenSol from './Token.sol/index.js';
export { TokenFaucet__factory } from './TokenFaucet__factory.js';